apocas/dockerode

examples/timeout.js
After seeing the example use a timeout of just 1, I assumed it was in seconds (like unix `timeout`) and didn't learn otherwise until reading the source of docker-modem. Of course, everything in node is in milliseconds, but it's always best to specify.
=> Specifies timeout is in milliseconds

lib/docker.js
Hi, I noticed that there is a way to get a container and an image without querying the Docker API, but for an exec instance this is missing.
I just added it to be able to do:
`var execId = docker.getExec('71501a8ab0f8');`
=> Add method to get exec instance

README.md
This is related to a pull request I sent to docker-modem:
https://github.com/apocas/docker-modem/pull/41
=> add docs for authconfig base64 encoded key

lib/exec.js
If used with the 'Detach: true' options, the /exec/:id/start endpoint returns 204 (No Content) rather than 200. Dockerode should treat this as a success rather an unhandled error.
=> Allow 204 as return code for /exec/:id/start

lib/docker.js
In the latest Docker, they've started to actually enforce the `VolumesFrom` parameter to be an array. It's always been an array, its just that the daemon has been loose about it until now.
I recommend cutting this as a new release ASAP as all use of `docker.run` is broken on Docker 1.7 using `dockerode` until this is fixed.
=> Fix VolumesFrom crash in Docker 1.7

lib/container.js
In addition to adding support for the `opts` to `container.stats()`, the repeated task of dealing with optional `opts` and the tailing `callback` arguments has been factored out into its own helper function `processArgs()` in order to remove some redundancy.
=> add support for optional `opts` argument to `container.stats()`

lib/container.js, test/container.js, test/spec_helper.js
This broke in 2.2.0 due to the cleanup of argument parsing because `/commit` is a bit unusual compare to the other `Container` methods. I did a scan and couldn't find anything else that had the same problem.
I also had to modify the spec helper to allow it to use a proper `DOCKER_HOST` if set.
=> Fix container commit

examples/run_stdin.js
Noticed that the example code didn't work properly for resizing the terminal, so I made a quick fix.
=> Fixes resizing in stdin example

lib/container.js, lib/docker.js, lib/image.js, test/spec_helper.js
These endpoints are not documented to return 200's, but proxies like Docker Swarm don't always preserve the status codes (see docker/swarm#1055).
@apocas thoughts?
=> Broaden accepted status codes

lib/docker.js
Changes all callback invocations to have a common argument format, and fixes a bug where `data` is undefined when calling the callback after a `container.attach` failure.
=> docker.run: fix callbacks

lib/container.js
The Docker API returns a 204 when the container is renamed, not a 200, which causes this method to throw an error.
=> Correct status code

lib/docker.js
The tests are explicitly checking for null, which is what all the other
methods use as a non-Error value.
=> fix failing createVolume tests

README.md, lib/container.js, lib/exec.js, test/container.js
This is supported by the /exec/(id)/start and /containers/(id)/attach
endpoints, allowing the HTTP request/response to be hijacked and turned
in to a regular TCP socket. This allows for useful features such as
half-closed sockets, which properly represents how a command's stdin
can be closed and it can still write output to stdout.
Requires HTTP->TCP connection 'upgrading' from docker-modem, which is
proposed in apocas/docker-modem#54.
=> add support for raw TCP socket upgrading

lib/container.js, test/container.js
Newly released Docker 1.9.x and APIs add support for getting container size information as part of the docker [inspect](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#inspect-a-container) API call.
This pull request adds support calling this API by passing in a `{size: true}` `opts`, which turn into URL query params sent to the API. This change is fully backwards compatible.
=> Allow an optional opts argument to Container.inspect

examples/listContainers.js, test/docker.js
requires docker-modem 0.3
@apocas as promised,  tests and example usage for the updated querysting behavior. 
Many thanks for merging my PR and for this module :) It's a ton of fun to play with docker in node.
=> add test and examples for filtering by map

lib/docker.js, test/docker.js
This is useful when you need to run commands once the container already is running, not just created.
=> Adds on 'start' event to docker.run

lib/task.js
The old references to 'nodes' are replaced by 'tasks'.
'opts' is not part of the tasks.inspect API.
=> Tasks.inspect calls the 'tasks' path.

lib/container.js, package.json
isStream is hardcoded to true, so there is no way to get stats without streaming.
This small change resolves that while still allowing the default streaming functionality
Issue #255
=> fix container stats to work with stream option true or false

lib/docker.js, lib/service.js
When using Dockerode, I wanted to create and update services using images from a private registry. To do so, you need to pass an authconfig to docker-modem, which will generate an X-Registry-Auth token when talking with the API.
This merge request enables us to add authconfig as a first parameter to `docker.CreateService` and `service.UpdateService`
=> Pass auth header on service creation and update

lib/docker.js, test/swarm.js
Some context:
To join a swarm, you need a _joinToken_. You find the joinToken with `GET /swarm`.
=> add swarmInspect hidden api.

lib/node.js, test/swarm.js
Some context:
In the API, `/swarm/leave` doesn't remove the node in the manager. If you loop `swarm/join` and `swarm/leave`, you'll find many node in the '_down_' state.
The method to remove a node in a manager is `DELETE /nodes/<id>`.
=> add Node.remove hidden API

README.md, examples/build/build_img_files.js, lib/docker.js, package.json, test/Dockerfile, test/docker.js
Example:
``` JavaScript
docker.buildImage({
context: __dirname,
src: ['Dockerfile', 'file1', 'file2']
}, {t: imageName}, function (err, response) {
//...
});
```
If this PR is accepted, I will send another PR to support `src` as directories
Inspired by https://github.com/JoTrdl/grunt-dock
=> Support building image from multiple files

lib/container.js, lib/exec.js, lib/image.js, lib/network.js, lib/node.js, lib/plugin.js, lib/secret.js, lib/service.js, lib/task.js, lib/volume.js
container.inspect() is supposed to return a Promise not a stringified object
=> Fix inconsistent behaviour of Container.inspect

lib/docker.js
`buildImage()` currently returns undefined when called without a callback, needs to return the result of `build()` instead, so we get a Promise
=> Promise needs to be returned

lib/network.js
when acting upon promises, a network refuses to be removed and gives `Cannot read property 'dial' of undefined` error
=> should use self instead of this

lib/docker.js
On case of using the function createImage with options object and no callback, the user will be able to give the credential via the `authconfig` option
=> On createImage, adding use of 'authconfig'.

lib/docker.js
When createContainer points to Docker Swarm Manager, it can pull missing image, but it needs `authconfig`.
=> Support authconfig in createContainer

lib/docker.js
The current code requires a file to be specified however it is now possible to build an image only using a git URL. With this change, file can be set to `null` to not send any tar archive and instead use the `remote` parameter.
Closes #380
=> Add ability to omit file to allow for remote context

lib/docker.js
Since V1.25 of Docker Engine API is available the rest /system/df. It's useful for data usage infos notably in swarm mode.
=> EHNANCEMENT - Added systemDf method for data usage information

lib/container.js
Change needed to make restart timeout parameter work. E.g.
container.restart({t: 0}).then(...)
=> container restart options

lib/container.js, lib/service.js, lib/task.js
By default the follow option in the container and service endpoint is false. This fix follows this definition and sets the isStream variable accordingly.
Best
=> Respect follow option on logs endpoint (default false)

lib/docker.js
`tar.pack()` creates a tarball of all files in the current working directory. This can take a fair amount of IO and time, and cause problems (https://github.com/resin-io/resin-cli/issues/824).
Right now in `buildImage`, Dockerode creates a tarball initially (and therefore reads & compresses every file in the CWD) in all cases, and then only if you've passed the details of some files in your context (rather than passing a tarball directly) does it add more files to the tarball and use it.
This PR changes this so that:
* No tarball is created at all if you've passed one already
* If you do need to build a tarball from a set of files, it uses the built-in tar-fs functionality to do this, rather than calling `tar.pack()` to pack the cwd and then adding files to it.
Tar-fs docs might be useful …
=> Pack files only if required when building

README.md
The old link now resolves to https://docs.docker.com/develop/sdk/ which isn't the correct page.
=> Update Docker API documentation link

README.md
Adds information about the possible values to pass as the `create_options` or `start_options`.
I had to take a look into the source code of this repo (and some additional digging around) to find out what values I have to pass to the `create_options` object.
=> Improves docker.run documentation in README

README.md
1. container must be started before creating execution
2. callback of exec.start is not actually stream, but stream.output is.
=> Fix README about container.exec

README.md
Originated from [this issue](https://github.com/apocas/dockerode/issues/458) as I had the same problems figuring out what `buildImage` returns
=> Adds buildImage documentation.

README.md, lib/container.js
- Adds support for the `condition` option to `Container#wait()` as described in docker's [`POST /containers/{id}/wait` endpoint](https://docs.docker.com/engine/api/v1.37/#operation/ContainerWait).
=> Add support for `Container#wait(options)`

lib/docker.js
This resolves #447 by adding an authconfig for search call in Dockerode.
=> Issue #447 authconfig for searchImages() call

examples/run.js, lib/docker.js
I spent a while digging down into dockerode and docker-modem trying to find a way to specify a name for Container Create which requires a querystring argument.  
I had a solution with the _query object that worked if I specified 'name' lower case, but it looked quite un-documented and hacky, so I figured I'd add a more intuitive way to specify the name of new containers with a 'Name' property next to all the others.
(https://docs.docker.com/engine/api/v1.29/#operation/ContainerCreate)
=> Offer a more intuitive way to name new containers

lib/docker.js
I found that dockerode's pull method doesn't use the default tag `latest` when no tag is given. This seemed to result in Docker downloading a bunch of images when pull was used without a tag, while in reality the user probably only wanted the latest image. It's also different from Docker CLI since that does use `latest` as the default tag when none is given.
This change modifies the pull method to use the default tag `latest` when none is given
=> Added default tag 'latest' to pull method to be more in line with Docker CLI

README.md
correcting the hijack example in the documentation
=> documentation fix: stream.output was undefined

lib/exec.js, test/container.js
=> Change the value of a resolved `exec()` call to be a stream

lib/network.js, test/networks.js
As described [here](https://docs.docker.com/engine/reference/commandline/network_inspect/).
The verbose flag provides valuable information when using an overlay network in a swarm environment. Currently it is impossible to access service task information using dockerode.
I'm not really sure how to test for the success of a verbose inspect, without setting up a whole swarm environment.
=> Add verbose option to network inspect

lib/docker.js
Added endpoint for [/images/get](https://docs.docker.com/engine/api/v1.40/#operation/ImageGetAll)
This was also requested in issue #470
=> getImages added to docker

lib/docker.js
fixed `Cannot read property 'fromSrc' of undefined` exception when calling `importImage(path)`
=> importImage: fixed default options

README.md
The current link does not exits and the user is redirected to the beginning of the page instead of the Hijacking paragraph.
=> Update the link for the the Docker Hijacking

lib/docker.js
A small fix for `pruneBuilder` function that currently fails because it tries to use non-existent `args` variable.
=> Fix pruneBuilder callback check

README.md
Describes the need to explicitly mention the files involved in the build.  The command line build extracts the build path from the context. In Dockerode the path is changed to the temp environment were the build occurs.
=> Tips on building a docker image

lib/docker.js
Tar-fs packs files in current directory by default if nothing is specified as first argument. Thus, when initializing `pack` at the start of the `buildImage` method, it started packing the entire current directory.
In my case, I package my app with Nexe and it tried to pack the entire virtual directory where my code was stored to be ran by Node and crashed because it couldn't find real files in it.
In other cases, this is just an unneeded waste of time whether the context is specified or not.
=> Disabling auto-pack when building image

lib/container.js
The `POST /container/:id/exec` endpoint can respond with with a 409 status code if the container isn't running (docs [here](https://docs.docker.com/engine/api/v1.37/#operation/ContainerExec)), but that isn't included as a recognized code so the `Error` that gets thrown has an empty `reason` property and the message is less descriptive than it could be.
I used the same `reason` as is used for 409s when trying to start an `Exec` for a container that isn't running.
=> Add 409 to status codes for /containers/:id/exec

lib/config.js, lib/container.js, lib/docker.js, lib/exec.js, lib/image.js, lib/network.js, lib/node.js, lib/plugin.js, lib/secret.js, lib/service.js, lib/task.js, lib/volume.js, test/container.js
This adds support for an `abortSignal` option in every API method. This fixes #629.
**This depends on the docker-modem change in https://github.com/apocas/docker-modem/pull/132/**. You'll need to link that dependency in to test this successfully.
I've added a test just for the `container.wait()` method, since that's the most obviously interesting use case, but I think being able to abort all types of requests can be useful in various different contexts.
=> Allow aborting all API requests by passing an abortSignal

lib/docker.js, test/docker.js
Thanks for the great lib!
Im writing some utils to build images, making use of dockerode's `buildImage()`. When testing my util, I was constantly running into a `500 error: Dockerfile not found`. Was super confused by this since I can clearly see the Dockerfile sitting in the `context` directory. It wasn't a file permission issue either. 
After digging around, I noticed the src array was being cleared after passing it into `buildImage()` due to its use of tar-fs's `statAll()` which in its current implementation mutates its `entries` array parameter. A PR has been opened for it but seems to have gone stale: https://github.com/mafintosh/tar-fs/pull/78, hence I'm opening the fix here instead to prevent others from facing this gotcha.
dockerode.buildImage …
=> Fix docker.buildImage() mutating src array due to tar-fs behaviour

lib/docker.js, package-lock.json, package.json, test/.dockerignore, test/docker.js
Fixes #545 
Using [@balenaa/dockerignore](https://github.com/balena-io-modules/dockerignore) to respect `.dockerignore` rules when building a new image from source
=> Added .dockerignore support for build

.gitignore, Vagrantfile, lib/docker.js, lib/util.js, package-lock.json, test/docker.js, test/fixtures/dockerignore/.dockerignore, test/fixtures/dockerignore/Dockerfile, test/fixtures/dockerignore/MC-hammer.txt, test/util.js
Improves over #606 which was intended for #545. 
Currently, we only filter what comes in `src` array, which might unexpectedly let pass files within directories. Also, it removes the need for `sync` functions. 
BTW I felt the need to update the `Vagrantfile` but I don't have any strong feeling about dropping that commit if required, since it is outside of the problem I want to address here.
=> Improve dockerignore support

lib/node.js
This is the only location I found in the repo where we get `abortSignal` from `args` instead of `args.opts` (out of 101 locations) which ends up being undefined and so ignored.
=> fix: node inspect is not using abort signal

lib/docker.js
This would allow calling Docker API via custom transports, e. g. [Portainer's authenticating proxy](https://app.swaggerhub.com/apis-docs/portainer/portainer-ce/2.16.1) (see section “Execute Docker requests”). Of course, we could add just those to the docker-modem itself, but I think a modular approach would be better here, and not really more verbose:
```js
const PortainerModem = require("@aedge/docker-modem-portainer");  // not implemented yet
const Docker = require("dockerode");
const docker = new Docker({
modem: new PortainerModem({
apiEndpoint: "https://portainer.lvh.me/api",
token: "eyJhbGciOiJ...",
}),
});
```
=> Allow passing a Modem instance directly

lib/docker.js, test/docker.js
Uses a single Promise as in v3.3.3, but maintains the asynchronous approach to `.dockerignore` processing added in v3.3.4.
Also added unit tests for the no-callback, Promise based path.
Fixes #696
=> Remove promise nesting in buildImage() when no callback

lib/config.js
It seems like this is just a simple mistake.
create, update and list, all gets their abortSignal from the args.
closes #739
=> Bugfix config remove

examples/run_stdin.js
In **run_stdin** example error not managed, so when run this example and if image not found locally it give error but it show different error and create confusion. So i managed  error so it will give **Unable to find image** error.
=> error managed in run_stdin example

README.md
The current reference to "HTTP connection hijacking" in the README file points to a deprecated API version page. This PR updates the reference to the latest API doc.
=> Update doc reference to "HTTP connection hijacking"

lib/docker.js, lib/proto/auth.proto, lib/session.js, package-lock.json, package.json, test/buildkit.Dockerfile, test/docker.js
I managed to get BuildKit build to work! It is not perfect yet, but it works most of the time for me.
To do this, dockerode needs to create a gRPC server and serve over a hijacked session connection to the docker backend and attach the sessionId to the build request. Even a gRPC server without any implemented services will do, but it can also be used to return credentials to docker, which is needed when using private Images or Registries.
The are some open todos and problems:
- "Error while dialing only one connection allowed"
- "http2: frame too large" 
Solves #601
=> POC: BuildKit support

lib/docker.js
This 'extend' variable is not being defined which is causing errors in node v20.
=> Declare 'extend' variable in docker.js

lib/docker.js, test/docker.js
Docker [ImageBuild](https://docs.docker.com/reference/api/engine/version/v1.48/#tag/Image/operation/ImageBuild) endpoint requires that the `cachefrom` option is a "JSON serialized array". This requirement seems to be an exception to the way arrays are consumed by the API (usually querystring serialized).
This change is needed after https://github.com/apocas/docker-modem/pull/181 that makes querystring serialized arrays the default.
This commit adds an exception for this option on `Docker.buildImage`.
Change-type: patch
Closes: #792
=> Use JSON serialization for cachefrom option

README.md, lib/image.js, test/docker.js, test/image.js
- Modify the `image.inspect` method to accept options, allowing for more flexible image inspection, including the ability to specify manifests.
- Update tests to verify the new functionality.
- Update the README to reflect the new functionality
=> Update image.inspect method to accept options
